### ISSUE TITLE
Tackable entity notification from SQL server

### ISSUE THREAD

**Issue by weedkiller** [SaladLab/TrackableData#1]
Hello, this is very nice 👍 

Do I need sql dependency, or will sql auto notify me - for e.g. if I have list of applications, how will I know what the row changes for each application are - will your tool simply update me with the trackable attribute?

**Comment by veblush** [comment]
Thanks!

And no to your question. TrackableData.Sql does not support change-monitor from SQL. It just forward all changes made by TrackableData to SQL.

**Comment by weedkiller** [comment]
This more like tracking stateless states too :) it would be nice to have some backing meta data, to tell the instance to gotoNext()
